/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-11-22 19:59:01 UTC)
 * on 2013-12-03 at 23:41:58 UTC 
 * Modify at your own risk.
 */

package com.g5.ridewithme.customerendpoint;

/**
 * Service definition for Customerendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link CustomerendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Customerendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the customerendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://fiuridewithme.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "customerendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Customerendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Customerendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getCustomer".
   *
   * This request holds the parameters needed by the the customerendpoint server.  After setting any
   * optional parameters, call the {@link GetCustomer#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetCustomer getCustomer(java.lang.Long id) throws java.io.IOException {
    GetCustomer result = new GetCustomer(id);
    initialize(result);
    return result;
  }

  public class GetCustomer extends CustomerendpointRequest<com.g5.ridewithme.customerendpoint.model.Customer> {

    private static final String REST_PATH = "customer/{id}";

    /**
     * Create a request for the method "getCustomer".
     *
     * This request holds the parameters needed by the the customerendpoint server.  After setting any
     * optional parameters, call the {@link GetCustomer#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetCustomer#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetCustomer(java.lang.Long id) {
      super(Customerendpoint.this, "GET", REST_PATH, null, com.g5.ridewithme.customerendpoint.model.Customer.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetCustomer setAlt(java.lang.String alt) {
      return (GetCustomer) super.setAlt(alt);
    }

    @Override
    public GetCustomer setFields(java.lang.String fields) {
      return (GetCustomer) super.setFields(fields);
    }

    @Override
    public GetCustomer setKey(java.lang.String key) {
      return (GetCustomer) super.setKey(key);
    }

    @Override
    public GetCustomer setOauthToken(java.lang.String oauthToken) {
      return (GetCustomer) super.setOauthToken(oauthToken);
    }

    @Override
    public GetCustomer setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetCustomer) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetCustomer setQuotaUser(java.lang.String quotaUser) {
      return (GetCustomer) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetCustomer setUserIp(java.lang.String userIp) {
      return (GetCustomer) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetCustomer setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetCustomer set(String parameterName, Object value) {
      return (GetCustomer) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertCustomer".
   *
   * This request holds the parameters needed by the the customerendpoint server.  After setting any
   * optional parameters, call the {@link InsertCustomer#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.g5.ridewithme.customerendpoint.model.Customer}
   * @return the request
   */
  public InsertCustomer insertCustomer(com.g5.ridewithme.customerendpoint.model.Customer content) throws java.io.IOException {
    InsertCustomer result = new InsertCustomer(content);
    initialize(result);
    return result;
  }

  public class InsertCustomer extends CustomerendpointRequest<com.g5.ridewithme.customerendpoint.model.Customer> {

    private static final String REST_PATH = "customer";

    /**
     * Create a request for the method "insertCustomer".
     *
     * This request holds the parameters needed by the the customerendpoint server.  After setting any
     * optional parameters, call the {@link InsertCustomer#execute()} method to invoke the remote
     * operation. <p> {@link InsertCustomer#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.g5.ridewithme.customerendpoint.model.Customer}
     * @since 1.13
     */
    protected InsertCustomer(com.g5.ridewithme.customerendpoint.model.Customer content) {
      super(Customerendpoint.this, "POST", REST_PATH, content, com.g5.ridewithme.customerendpoint.model.Customer.class);
    }

    @Override
    public InsertCustomer setAlt(java.lang.String alt) {
      return (InsertCustomer) super.setAlt(alt);
    }

    @Override
    public InsertCustomer setFields(java.lang.String fields) {
      return (InsertCustomer) super.setFields(fields);
    }

    @Override
    public InsertCustomer setKey(java.lang.String key) {
      return (InsertCustomer) super.setKey(key);
    }

    @Override
    public InsertCustomer setOauthToken(java.lang.String oauthToken) {
      return (InsertCustomer) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertCustomer setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertCustomer) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertCustomer setQuotaUser(java.lang.String quotaUser) {
      return (InsertCustomer) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertCustomer setUserIp(java.lang.String userIp) {
      return (InsertCustomer) super.setUserIp(userIp);
    }

    @Override
    public InsertCustomer set(String parameterName, Object value) {
      return (InsertCustomer) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listCustomer".
   *
   * This request holds the parameters needed by the the customerendpoint server.  After setting any
   * optional parameters, call the {@link ListCustomer#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListCustomer listCustomer() throws java.io.IOException {
    ListCustomer result = new ListCustomer();
    initialize(result);
    return result;
  }

  public class ListCustomer extends CustomerendpointRequest<com.g5.ridewithme.customerendpoint.model.CollectionResponseCustomer> {

    private static final String REST_PATH = "customer";

    /**
     * Create a request for the method "listCustomer".
     *
     * This request holds the parameters needed by the the customerendpoint server.  After setting any
     * optional parameters, call the {@link ListCustomer#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListCustomer#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListCustomer() {
      super(Customerendpoint.this, "GET", REST_PATH, null, com.g5.ridewithme.customerendpoint.model.CollectionResponseCustomer.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListCustomer setAlt(java.lang.String alt) {
      return (ListCustomer) super.setAlt(alt);
    }

    @Override
    public ListCustomer setFields(java.lang.String fields) {
      return (ListCustomer) super.setFields(fields);
    }

    @Override
    public ListCustomer setKey(java.lang.String key) {
      return (ListCustomer) super.setKey(key);
    }

    @Override
    public ListCustomer setOauthToken(java.lang.String oauthToken) {
      return (ListCustomer) super.setOauthToken(oauthToken);
    }

    @Override
    public ListCustomer setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListCustomer) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListCustomer setQuotaUser(java.lang.String quotaUser) {
      return (ListCustomer) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListCustomer setUserIp(java.lang.String userIp) {
      return (ListCustomer) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListCustomer setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListCustomer setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListCustomer set(String parameterName, Object value) {
      return (ListCustomer) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeCustomer".
   *
   * This request holds the parameters needed by the the customerendpoint server.  After setting any
   * optional parameters, call the {@link RemoveCustomer#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveCustomer removeCustomer(java.lang.Long id) throws java.io.IOException {
    RemoveCustomer result = new RemoveCustomer(id);
    initialize(result);
    return result;
  }

  public class RemoveCustomer extends CustomerendpointRequest<Void> {

    private static final String REST_PATH = "customer/{id}";

    /**
     * Create a request for the method "removeCustomer".
     *
     * This request holds the parameters needed by the the customerendpoint server.  After setting any
     * optional parameters, call the {@link RemoveCustomer#execute()} method to invoke the remote
     * operation. <p> {@link RemoveCustomer#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveCustomer(java.lang.Long id) {
      super(Customerendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveCustomer setAlt(java.lang.String alt) {
      return (RemoveCustomer) super.setAlt(alt);
    }

    @Override
    public RemoveCustomer setFields(java.lang.String fields) {
      return (RemoveCustomer) super.setFields(fields);
    }

    @Override
    public RemoveCustomer setKey(java.lang.String key) {
      return (RemoveCustomer) super.setKey(key);
    }

    @Override
    public RemoveCustomer setOauthToken(java.lang.String oauthToken) {
      return (RemoveCustomer) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveCustomer setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveCustomer) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveCustomer setQuotaUser(java.lang.String quotaUser) {
      return (RemoveCustomer) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveCustomer setUserIp(java.lang.String userIp) {
      return (RemoveCustomer) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveCustomer setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveCustomer set(String parameterName, Object value) {
      return (RemoveCustomer) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateCustomer".
   *
   * This request holds the parameters needed by the the customerendpoint server.  After setting any
   * optional parameters, call the {@link UpdateCustomer#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.g5.ridewithme.customerendpoint.model.Customer}
   * @return the request
   */
  public UpdateCustomer updateCustomer(com.g5.ridewithme.customerendpoint.model.Customer content) throws java.io.IOException {
    UpdateCustomer result = new UpdateCustomer(content);
    initialize(result);
    return result;
  }

  public class UpdateCustomer extends CustomerendpointRequest<com.g5.ridewithme.customerendpoint.model.Customer> {

    private static final String REST_PATH = "customer";

    /**
     * Create a request for the method "updateCustomer".
     *
     * This request holds the parameters needed by the the customerendpoint server.  After setting any
     * optional parameters, call the {@link UpdateCustomer#execute()} method to invoke the remote
     * operation. <p> {@link UpdateCustomer#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.g5.ridewithme.customerendpoint.model.Customer}
     * @since 1.13
     */
    protected UpdateCustomer(com.g5.ridewithme.customerendpoint.model.Customer content) {
      super(Customerendpoint.this, "PUT", REST_PATH, content, com.g5.ridewithme.customerendpoint.model.Customer.class);
    }

    @Override
    public UpdateCustomer setAlt(java.lang.String alt) {
      return (UpdateCustomer) super.setAlt(alt);
    }

    @Override
    public UpdateCustomer setFields(java.lang.String fields) {
      return (UpdateCustomer) super.setFields(fields);
    }

    @Override
    public UpdateCustomer setKey(java.lang.String key) {
      return (UpdateCustomer) super.setKey(key);
    }

    @Override
    public UpdateCustomer setOauthToken(java.lang.String oauthToken) {
      return (UpdateCustomer) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateCustomer setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateCustomer) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateCustomer setQuotaUser(java.lang.String quotaUser) {
      return (UpdateCustomer) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateCustomer setUserIp(java.lang.String userIp) {
      return (UpdateCustomer) super.setUserIp(userIp);
    }

    @Override
    public UpdateCustomer set(String parameterName, Object value) {
      return (UpdateCustomer) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Customerendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Customerendpoint}. */
    @Override
    public Customerendpoint build() {
      return new Customerendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link CustomerendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setCustomerendpointRequestInitializer(
        CustomerendpointRequestInitializer customerendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(customerendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
